# Generated by Django 5.2 on 2025-04-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_manage_users', 'Can manage users')]},
        ),
    ]
