# Generated by Django 5.2 on 2025-04-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_ubicacion_asistencia_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
