# Generated by Django 5.2 on 2025-04-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistencia_confirmada'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='asistencia__fecha_c5c62b_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['usuario'], name='asistencia__usuario_58140f_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['dni'], name='asistencia__dni_a92db6_idx'),
        ),
    ]
