# Generated by Django 5.2 on 2025-04-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_manage_users', 'Can manage users'), ('can_scan_qr', 'Can scan QR codes')]},
        ),
    ]
